#!/bin/bash
bundle install --jobs=3 --retry=3
# skip if build is triggered by pull request
if [ $TRAVIS_PULL_REQUEST == "true" ]; then
  echo "this is PR, exiting"
  exit 0
fi

# enable error reporting to the console
set -e

# cleanup "_site"
rm -rf _site
mkdir _site

# clone remote repo to "_site"
git clone https://${150dd6b1e4c17887c279d625c1d93a76da5abfdf}@github.com/ayastreb/11route.git --branch gh-pages _site

# build with Jekyll into "_site"
bundle exec jekyll build

# push
cd _site
git config user.email "shaoyihuan2@gmeil.com"
git config user.name "Pixel_Hobbit"
git add --all
git commit -a -m "Travis #$TRAVIS_BUILD_NUMBER"
git push --force origin gh-pages
